### ISSUE TITLE
spurious newline added when diff contains a list with new elements

### ISSUE THREAD

**Issue by t3chguy** [fiduswriter/diffDOM#100]
See https://jsfiddle.net/3u95j6z0/

When applied, this diff looks like
![image](https://user-images.githubusercontent.com/2403652/81944925-52637f80-95f5-11ea-8afc-b0b54374158f.png)

Additionally, this diff could be simplified to just a single step and that would hugely clean it up.

**Comment by johanneswilm** [comment]
Hey, the newline that is being added is because there is another textnode with a newline in it. This currently spans over 3 diffs, which could be cut down to 2 under perfect conditions. I think this looks quite acceptable though.

**Comment by johanneswilm** [comment]
If you want to investigate it more and write a patch, I'd be happy to merge it @t3chguy .

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/94413573-2c3d1700-0173-11eb-874b-051b29f33caf.png)

I disagree that it is acceptable. It looks like it regressed further recently, originally it looked like shown in the OP

![image](https://user-images.githubusercontent.com/2403652/94413652-45de5e80-0173-11eb-9283-fbcb5a67c1fb.png)

**Comment by johanneswilm** [comment]
@t3chguy I received a message that you commented on this issue, but the comment seems to have disappeared.

**Comment by t3chguy** [comment]
Yup, I deleted it, it was moot and a bad reproduction case.
