### ISSUE TITLE
Empty li tags are wrongly diffed

### ISSUE THREAD

**Issue by vielhuber** [fiduswriter/diffDOM#104]
Closing tags for empty `<li>`-Tags are optional (see https://www.w3.org/TR/2014/REC-html5-20141028/syntax.html#optional-tags).

**Input:**

```html
<ul class="foo">
    <li></li>
    <li></li>
    <li></li>
</ul>
```

```js
dd = new diffDOM.DiffDOM();
let elementA = document.querySelector('.foo');
diff = dd.diff(elementA, '<ul class="bar"><li><li><li></ul>');
dd.apply(elementA, diff);
```

**Output:**

```html
<ul class="bar">
    <li>
        <li>
            <li></li>
        </li>
    </li>
</ul>
```

**Expected output:**

```html
<ul class="foo">
    <li></li>
    <li></li>
    <li></li>
</ul>
```

**Workaround:**

```js
dd = new diffDOM.DiffDOM();
let elementA = document.querySelector('.foo');
diff = dd.diff(elementA, new DOMParser().parseFromString('<ul class="bar"><li><li><li></ul>', 'text/html').body.childNodes[0]);
dd.apply(elementA, diff);
```

**Comment by johanneswilm** [comment]
@vielhuber Ok, optional. But not very helpful not to include them, if you ask me. Is this user generated content you are dealing with? Could you write a patch to work around this?

**Comment by vielhuber** [comment]
Nope, this is the output of phps `DOMDocument`, which always generates this code. No way to turn that off.

**Comment by johanneswilm** [comment]
Ok, I tried working on this, but unfortunately there are a number of issues with the practical implementation as browsers also allow things like `<li><li></li></li>` (unless normalized), and so we have seen examples of that in the wild. So the interpreter will have to make a guess as to whether it should normalize that or not. You can see my initial work in the `normalize-strings` branch. I don't think that I will work any more on that though, so it would have to be someone affected by this who writes the additional code.

Alternatively, convince the PHP devs to export sane HTML.

**Comment by vielhuber** [comment]
Hello! First of all, thank you for your time and work on that topic and on the project in general.
This is understandable that this could be a rabbit hole.
Unfortunately I don't think domdocument changes anytime soon, but there are some
workaround tricks to get around that problem.
Let's leave is at that; This ticket is reasonable to close but archived to anybody else can see that this problem exists.

**Comment by vielhuber** [comment]
Workaround for DOMDocument:

```php
$DOMDocument->loadHTML(file_get_contents('tpl.html'));
// this forces domdocument to close empty li tags
$nodes = $DOMXPath->query('/html/body//*[not(node())]');
foreach($nodes as $nodes__value) { $nodes__value->nodeValue = ''; }
$html = $DOMDocument->saveHTML();
```
