### ISSUE TITLE
Diff cannot be applied

### ISSUE THREAD

**Issue by rzhornyk** [fiduswriter/diffDOM#105]
Hi @johanneswilm 

I found case similar to #90 and #97 but with difference that diff cannot be applied.
See JS fiddle with code to reproduce https://jsfiddle.net/0hg5xkpn/31/

There a lot of repeating diffs (3962) and after some iteration it tries to remove option as text element, but condition in applyDiff method not allow to do that 
https://github.com/fiduswriter/diffDOM/blob/64c0aee06b87de411b897267bfd4dec109fb965b/src/diffDOM/dom/apply.js#L127-L128 
As a result entire apply stops and HTML changes became partially applied.

Could you take a look?

**Comment by johanneswilm** [comment]
thanks @rzhornyk ! This has been fixed in 4.2.2.

**Comment by rzhornyk** [comment]
Cool! 
@johanneswilm thank you for quick fix!
