### ISSUE TITLE
Documentation for each action

### ISSUE THREAD

**Issue by uahnbu** [fiduswriter/diffDOM#107]
Your app is really great and useful. I'm currently implementing it in detecting HTML change and visualize it. However, I'm confused of what the data the function `postDiffApply` will return. It'd be grateful if you make some documentation about the actions and the nodes and the newNodes.
My current code for selecting the modify element is as below.
```javascript
postDiffApply(data) {
  const action = data.diff.action;
  let el = data.newNode || data.node;
  if (action === 'removeElement' || action.includes('Text')) && (el = el.parentElement);
```

**Comment by johanneswilm** [comment]
Hey @uahnbu ,
thanks for your support. The hook you mention was contributed by another project that uses it to hook into the core of diffDOm and extend it. I don't currently have plans for adding more documentation, so the source code is probably your best bet. If you look through this switch, you should be able to figure out what each action does: https://github.com/fiduswriter/diffDOM/blob/gh-pages/src/diffDOM/dom/apply.js#L39
