### ISSUE TITLE
`window is not defined`

### ISSUE THREAD

**Issue by sntran** [fiduswriter/diffDOM#111]
When trying to use `diff-dom` in a web extension for vscode, the following error occurs:

```
ReferenceError: window is not defined
	at node_modules/diff-dom/dist/index.js (extension.js:641:76)
```

That line is:

```js
document: !(!window || !window.document) && window.document
```

**Comment by johanneswilm** [comment]
@sntran It looks to me like that is something dependent on your package. The only place this shows up in the original file is here: https://github.com/fiduswriter/diffDOM/blob/85df21acd59236ff867f0b504f24c3c8db7b51d5/src/diffDOM/index.js#L25 . And that line should take care of both cases where there is a `window`/`window.document` and one where there is not one.

**Comment by sntran** [comment]
The file distributed in NPM has that line: https://cdn.jsdelivr.net/npm/diff-dom@4.2.3/dist/index.js#:~:text=document%3A!(!window%7C%7C!window.document)%26%26window.document.

**Comment by lexoyo** [comment]
> 



> @sntran It looks to me like that is something dependent on your package. The only place this shows up in the original file is here:
> 
> https://github.com/fiduswriter/diffDOM/blob/85df21acd59236ff867f0b504f24c3c8db7b51d5/src/diffDOM/index.js#L25
> . And that line should take care of both cases where there is a `window`/`window.document` and one where there is not one.

actually this should probably be `document: typeof window !== 'undefined' && window.document ? window.document : false`

**Comment by johanneswilm** [comment]
@lexoyo will fix now

**Comment by sntran** [comment]
Thanks!
