### ISSUE TITLE
diffDOM Demo bug

### ISSUE THREAD

**Issue by Luxemburgo** [fiduswriter/diffDOM#123]
In the http://fiduswriter.github.io/diffDOM/demo/index.html Demo, if you remove the `<i>test</i>` portion of the HTML, the youtube video resets (contrary to the above claim)

🤚

**Comment by johanneswilm** [comment]
Revolutionary greetings @Luxemburgo !
Thanks for the report. It has been fixed in 5.0.7.

**Comment by Luxemburgo** [comment]
> Revolutionary greetings @Luxemburgo ! Thanks for the report. It has been fixed in 5.0.7.

✊
