### ISSUE TITLE
Applying diff to VDOM (updated title)

### ISSUE THREAD

**Issue by s1m-e0n** [fiduswriter/diffDOM#124]
I'm trying to apply a diff on a virtual dom but the apply function fails on [this](https://github.com/fiduswriter/diffDOM/blob/24a11daa2d77df5885e019c086bfae514e43540c/src/diffDOM/dom/apply.ts#L63) line.
```javascript
let vdom = nodeToObj(document.body);
const dd = new DiffDOM();

const callbackMutation = () => { // executes everytime a dom change occurs
  const patch = dd.diff(vdom, document.body);
  dd.apply(vdom, patch);
};
```
The first time the callback is executed the apply works but after that every call fails. Is there something I am misunderstanding?

**Comment by johanneswilm** [comment]
Please provide a full demo using a service such as jsfiddle.

**Comment by s1m-e0n** [comment]
https://jsfiddle.net/oqg78yjd/
I hope this is a correct reproduction of the problem. The apply always fails in this case, even the first time.

**Comment by johanneswilm** [comment]
@s1m-e0n Ah, thatnks. I had a look and realized you are trying to apply the patch to a VDOM with the function that is meant for applying the patch to an actual DOM. The point of using VDOMs is that it's faster to convert DOM to VDOM and then to find the differences between two VDOMs rather than to compare two DOM objects. I don't think we export the apply function for applying diffs to a VDOM. 

Do you have a use-case where applying a diff to a VDOM makes sense? if so, what is it?

**Comment by s1m-e0n** [comment]
Ah I see, from the documentation it looked like it was possible.
My use case is that I want to extract and analyse changes made to the DOM of a website from a browser extension. For that I would need the previous and current DOM to generate the diff. Every time a change to the DOM occures I would copy the DOM to `previousDOM` to compare with the real DOM after the next change.  I thought it might be more efficient to maintain a Virtual Dom instead by applying the same changes made to the real DOM to my VDom, that way I would be saving that copy operation and perhaps also speed up the diff operation. I hope that makes sense.

**Comment by s1m-e0n** [comment]
@johanneswilm  Code example of what I wrote above:

**Old solution**
```javascript
var oldDom =  document.body.cloneNode(true);
function executeAtDomChange() {
  const diff = dd.diff(oldDom, document.body);
  doSomethingWithDiff(diff);
  oldDom = document.body.cloneNode(true);
}
```
**Better solution (I think)**
```javascript
var oldDom = nodeToObj(document.body);
function executeAtDomChange() {
  const diff = dd.diff(oldDom, document.body);
  doSomethingWithDiff(diff);
  apply(oldDom, diff);
}
```

**Comment by johanneswilm** [comment]
Hey @s1m-e0n ,
ok, shouldn't you be able to do:

```js
let oldDom = nodeToObj(document.body);
function executeAtDomChange() {
  const newDom = nodeToObj(document.body);
  const diff = dd.diff(oldDom, newDom);
  doSomethingWithDiff(diff);
  oldDom = newDow;
}
```

**Comment by johanneswilm** [comment]
The library gives you the ability to diff between real or virtual doms. Any real diff is converted to a virtual dom before diffing starts. So you can choose between either doing the conversion before diffing (using `nodeToObj`) or not. The reason you may choose to do the conversion is that you want to reuse it, store it, modify it after use, etc. . But I don't see why you would need to apply a diff to one of those virtual doms. At least not in the example given above.

**Comment by s1m-e0n** [comment]
Thank you for the great suggestion, in this case it would work.
Unfortunately though, the `doSomethingWithDiff` function is quite extensive and also may involve syncing the diffs to a server. It's possible that I may need to reconstruct the DOM(s) on the server given the diffs received from the extension and it would have been nice to just work with an `elementNodeType` instead of somthing else that works in node.js. I understand this is a very specific use case though.
Thanks for your help and for making this library!

**Comment by johanneswilm** [comment]
@s1m-e0n Ok, but can you not send both `oldDom` and `newDom` to the server? They are just JavaScript objects. Then you should have the `from` node, the `to` node and the in between on the server. And you wouldn't need to apply the diff on the server ever.... unless you are trying to use this to create something like a collaborative editor in which the server tries to merge different diffs from different users. If that is the case, I think you will quickly overload the server. Instead you should have the individual clients try to apply their diffs on top of the most recent version from the server. Something like this:

M1 Client 1 to Server: Apply `diff 1` on `base`.
M2 Server to all clients: Apply `diff 1` on `base` to form `new base`.
M3 Client 2 (sends before receiving M2): Apply `diff 1a` on `base`
M4 Server to client 2: Rejected.
Client 2 tries to apply `diff 1a` on top of `new base`
    Success => M5 Client 2: Apply `diff 1a` on `new base`
    Fail => Client 2 undoes `diff 1a` locally
    
    
It's a bit more complex than that in real life, but basically that's it. Again - no need to apply a diff on a virtual dom ever.

**Comment by s1m-e0n** [comment]
Hm, I was concerned about sending entire DOM objects to the server at such a high rate but if you say this isn't silly then that's good to me (first time working with JS and performance isn't the most critical thing right now anyway). 
This is just a project for Uni broadly investigating how to classify changes made to the DOM using the diffs. Nowhere near as complex as a collaborative editor.
You've been a great help, thanks :)

**Comment by johanneswilm** [comment]
In almost all cases, this shoudl; not be a concern. You should be more concerned about the server having to redo the calculation of applying the diff. An exception may be a super computer on a mission on Mars or similar where bandwidth is low but available computing speed is high.
The reason the virtual dom functions are not exported has to do with a lot of confusion previous users have had with this. If we do find a real usecase though, we can always change it.
