### ISSUE TITLE
Crash when applying diff, starting with v5.0.7

### ISSUE THREAD

**Issue by 6a5p1** [fiduswriter/diffDOM#142]
The diff apply operation results in a crash at the `relocateGroup` operation. 
node.removeChild - crashes, in chrome debugger (in my example) - node.childNodes[diff[options._const.from]] - the index is > than the number of childNodes.
Please take a look as I had to downgrade from 5.1.2 to 5.0.6 to find a working version

**Comment by johanneswilm** [comment]
@6a5p1 It's very difficult for me to work on this without an example. Could you provide me with at the very least an example of what you were diffing? I am assuming you did no manual change to anything at all.

**Comment by 6a5p1** [comment]
sure, I'll be back with an example asap

**Comment by 6a5p1** [comment]
Using version 5.1.2

OLD:
`



    
    <div class="test-c">
        
            
            
                
                    <div class="test-0">
    
    
        
        
        <div class="test-1">
            
                
                    <span>XX</span>
                
            
                
                    <span>XX</span>
                
            
                
                    <span>XX</span>
                
            
                
                    <span>XX</span>
                
                    <span>XX</span>
                
                    <span>XX</span>
                
                    <span>XX</span>
                
            
        </div>
    
</div>

                
            
                
            
                
            
                
            
                
            
                
            
                
            
                
            
                
            
                
            
        
    </div>


`


NEW: 
`



    
    <div class="test-c">
        
            
            
                
                    <div class="test-0">
    
    
        
        
        <div class="test-1">
            
                
                    <span>XX</span>
                
            
                
                    <span>XX</span>
                
                    <span>XX</span>
                
                    <span>XX</span>
                
                    <span>XX</span>
                
                    <span>XX</span>
                
                    <span>XX</span>
                
            
        </div>
    
</div>

                
            
                
            
                
            
                
            
                
            
                
            
                
            
                
            
                
            
                
            
        
    </div>


`

Error: 
`
TypeError: Failed to execute 'removeChild' on 'Node': parameter 1 is not of type 'Node'.
    at module.js:228:1
    at Array.map (<anonymous>)
    at applyDiff (module.js:227:1)
    at module.js:290:1
    at Array.every (<anonymous>)
    at applyDOM (module.js:289:1)
    at push../node_modules/diff-dom/dist/module.js.DiffDOM.apply (module.js:1866:1)
`

<img width="831" alt="Screenshot 2024-06-18 at 14 17 32" src="https://github.com/fiduswriter/diffDOM/assets/26039558/f2f0a225-a3a6-46b1-a887-167d2461893e">

**Comment by 6a5p1** [comment]
The divs are closed, the html is correct, don't know why they are displayed like this in github

**Comment by johanneswilm** [comment]
Ok, I will test. So the only difference is one of whitespace, correct?

**Comment by 6a5p1** [comment]
<img width="1438" alt="Screenshot 2024-06-18 at 14 48 26" src="https://github.com/fiduswriter/diffDOM/assets/26039558/536ec72e-83ed-45ca-b364-d881d5c17d86">

I added a printscreen with my actual html (before and after, old and new) to help you with debugging.
Note that the html starts and ends with blank linkes (\n), maybe they are important, don't know.

Thank you in advance!

**Comment by 6a5p1** [comment]
Hello! Do you have any update here? And thank you!

**Comment by johanneswilm** [comment]
@6a5p1 fixed in 5.1.4
