### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by michaelBenin** [fiduswriter/diffDOM#19]
I'd like to use this project with browserify and node in commonjs.

 It looks as if it already has the support here: https://github.com/fiduswriter/diffDOM/blob/gh-pages/diffDOM.js#L998

Is it possible to publish this on npm?

Thank you!

**Comment by johanneswilm** [comment]
Ok, the 1.0.0 vrsion should be available in the npm directory now. Let me know if this is working for you. generally speaking a DOM is needed for diffDOm to work, so it willlikely break if there is nothign like that available.

**Comment by michaelBenin** [comment]
Ah, thank's for clarifying. To make it isomorphic (execute in both browser and node) maybe we could look into using JsDom, or always return the rendered string without diffing it, or add functionality of diffing the strings. 

Either way I'm really excited about testing this library out today and seeing how responsive the maintainers are to issues, I have more confidence using it in my projects. 

Thank you.

**Comment by johanneswilm** [comment]
Yes, I was looking a bit at jsDOM. Unfortunately I currently don't really have a node environment set up to test things related to jsDOM, but please feel free to do that.

Generally speaking this library has been pretty stable for quite a while and no bugs have been reported for several months, which is wy there hasn't been happening much in the repo for a while. However in the last few days a contribution was made to minimize the number of affected elements. This has been merged and will likely lead to the release of a version 1.1.0 in the near future.

**Comment by michaelBenin** [comment]
That's awesome!

Yes I'd love to set something up with node although I have so many weekends to work with this :)

**Comment by michaelBenin** [comment]
Verified the published npm package is working with browserify: 

https://github.com/michaelBenin/node-startup/commit/6526fddd6ef7866b0ef2e0bf351b41ce862b16ea

**Comment by johanneswilm** [comment]
Ok, good to know! Using it in browserify had been done before, but not with this version and not with npm version. As I recall it, in browserify you have access to the standard DOM. It will be interesting to see if someone using a DOM-less system will be able to make it work using jsDOM or similar...
