### ISSUE TITLE
Checking for valid arguments?

### ISSUE THREAD

**Issue by michaelBenin** [fiduswriter/diffDOM#22]
https://github.com/fiduswriter/diffDOM/blob/gh-pages/diffDOM.js#L817

Recently I was passing undefined to apply as the second argument, and it errored out. It would be nice if we could let the user know bad input was put in. How do you feel about renaming apply to applyDiff?

**Comment by johanneswilm** [comment]
You mean type checking and if it's not a list of diffs or a single diff then return an error saying something a la "second argument needs to be a list of diffs"?
applyDiff already is a function name that is used, so we probably shouldn't use that again. But what's your reasoning?

**Comment by michaelBenin** [comment]
Yes to the first type checking of arguments. 

The reason for renaming apply is because apply is a method of calling a function.

```
diffDom.apply.apply(scope, [args]);
```

Not critical at all.

**Comment by johanneswilm** [comment]
Ok, I understand your wish for type checking. The thing is that we either accept an array of diffs or just a diff object. How much do you want to heck? I mean we can determine it's an array, but it may be an array containing completely different objects than what we need. What do you think would be useful?

**Comment by michaelBenin** [comment]
It would be optimized in v8 if it always had an array for an argument.

**Comment by johanneswilm** [comment]
@michaelBenin Do you have a link explaining that? Should we simply remove the option to allow single diffs that are not in an array and then it will be faster?
