### ISSUE TITLE
Detecting events bound to DOM?

### ISSUE THREAD

**Issue by Xeoncross** [fiduswriter/diffDOM#23]
I was thinking about using diffDom to apply DOM changes when my models change, but then I realized that it probably doesn't check for bound events and transfer the events over to the new elements (or if they were removed - then unbind them).

How would you handle something like this?

**Comment by johanneswilm** [comment]
You mean events that were attached to certain elements in the source-dom element and how to attach them in the target-dom element? The two may reside on two different machines.

**Comment by Xeoncross** [comment]
Two different machines?

I meant that if you had handlers bound to `ul` items - then the diff detected a new `li` was added - would it be able to bind the same event to it?

**Comment by johanneswilm** [comment]
@Xeoncross I think this depends on how you attach those events. If you use jQuery's ```$(document).on(event, selector, handler)``` this should also automatically match all future elements. Please reopen this issue if I have misunderstood you on this.
