### ISSUE TITLE
Is it possible to know if a specific diff is an innerHTML diff?

### ISSUE THREAD

**Issue by yattias** [fiduswriter/diffDOM#24]
Whenever the diff is ``innerHTML`` (or not an attribute diff) I would like to ignore that diff.
Is it possible to determine when a diff is innerHTML? As of now, I have noticed that innerHTML diffs typically show up at the end, after attribute diffs. Would that always be the case?

```
[Diff, Diff, Diff, Diff]
0: Diff
1: Diff
2: Diff
3: Diff // <= this one is innerHTML diff, I would like to remove it from the diff list
```

**Comment by johanneswilm** [comment]
You can find the different diff types and their codes used at the start of the soruce code: https://github.com/fiduswriter/diffDOM/blob/gh-pages/diffDOM.js#L5-L35 . Not sure which one you refer to as `innerHTML`, but it should be listed there.
