### ISSUE TITLE
vdom issues

### ISSUE THREAD

**Issue by johanneswilm** [fiduswriter/diffDOM#29]
Using a "virtual" dom nodes (in the form of JS Objects) instead of "real" DOM nodes (even though they off-screen and disconnected) has speed advantages. In the vdom branch diffDOM has been converted to do that for the building of the diff list. However, it is currently still buggier than the original version. When running random.html, at least two different types of errors show up every now and then. One of these bugs has been added to the top of the basic.html file.The other one was less easily reproducible but results in an error due to a missing parentNode around lines 1192/1210.

These issues are the main thing that prevent the vdom branch from being merged into the main branch.

@unbug is currently looking at the bug in basic.html.

**Comment by unbug** [comment]
hum..so far,this is what I got,first I though this's not the virtual dom bug,might be a render issue,when it's apply the diffdom,the browser takes time to get it done,but diffdom is too fast to wait for the next render loop(a apply callback show helps).So I use the timeout,it looks fine,but when it runs to 26th-vs-27,the diff never got though,and this is just a very small html,I am still digging,hope this helps.
Also, ```lastChild``` should be```lastElementChild``` in the ```print``` method.
```js
i = 26;
    function delay(fn,time){
      setTimeout(fn,time||1200);
    }
    function report(doundo){
      try {
        reportDiv();
        print("diff operations for div #" + i + " → div #" + (i + 1));
        console.log(divs.length,i,divs[i],divs[i + 1]);
        diffs = dd.diff(divs[i], divs[i + 1]);
        //  console.log(diffs);

        print("applying...");
        t1 = divs[i].cloneNode(true);
        console.log(t1.innerHTML,divs[i].innerHTML);
        dd.apply(t1, diffs);
        delay(function(){
          if (t1.innerHTML === divs[i + 1].innerHTML) {
            print('...success!');
            !doundo && testSuccess();
          } else {
            testFailure();
            console.log(diffs);
            console.log(t1.outerHTML);
            console.log(divs[i + 1].outerHTML);
            throw 'Outputs not matching';
          }

          doundo && delay(function(){
            print("undoing...");
            dd.undo(t1, diffs);
            delay(function(){
              if (t1.innerHTML === divs[i].innerHTML) {
                print('...success!');
                testSuccess();
              } else {
                testFailure();
                console.log(diffs);
                console.log(t1.outerHTML);
                console.log(divs[i].outerHTML);
                throw 'Outputs not matching';
              }
            },1000+i*50);
          },1000+i*50);
        },1000+i*50);


        //try {
      } catch (e) {
        console.log("error occured\n", e.toString());
        console.log(tl.toString());
        throw e;
      }
      delay(function(){
        i = i + 2;
        i < divs.length && report();
      },(doundo?3500:1000)+i*300);
    }
    report(false);
````

**Comment by johanneswilm** [comment]
@unbug: There are likely also bugs other places, but in the first example in basic.html, it is indeed a diffDOM bug. I have tried to remove as much as possible from the two divs that wouldn't work that still shows the bug and I have come up with these two divs:

```
<div><i></i><i><img></i><img>1</div>
<div><img><i></i><b></b>1</div>

**Comment by unbug** [comment]
I think this is an unfair diff,how can we tell different from this too markup?and which one should be apply on another one?
```html
<p></p>
    <p><i></i>
    </p>
    <p></p><i><img><span><b></b></span><img></i>
    <p></p><i><img><span></span></i>
    <p><i></i>
    </p>
    <p></p>
    <img><span><span></span></span>
    <img>
```
```html
    <img><i></i>
    <p><span><span><b></b></span></span>
    </p>
    <p></p><b><img><span></span></b>
    <p><b></b>
    </p>
    <p></p>
    <p></p>
    <p>wg</p><i><p></p></i>2nJ<i><img></i>
    <p></p><i><img></i>zV87J1UU3Ex
```

**Comment by johanneswilm** [comment]
What do you mean by an "unfair diff"?

**Comment by johanneswilm** [comment]
@unbug I solved the first half of the puzzle by comparing how the old and the new code tried to handle the diffing. It turned out that the main part of that was that the "elementDescripters" function had not been updated to handle vdom elements. 

I am still not sure what you are referring to, but the problem is still there in the basic.html file. I've updated it to only have this minimal example. It still hasn't been solved completely.

**Comment by johanneswilm** [comment]
@unbug OK, so I fixed the first bug by going through the same minuscule process. But there are more bugs, and if you load the basic.html file, you will ntoice that there is an issue down at diffing div 26 and 27. It was a diffDOM issue. In general, I doubt there will be any timing issues in here, simply because there are no threads in any of this. It's all just single thread, synchronous behavior.

**Comment by johanneswilm** [comment]
@unbug I see, you already looked at the bug for divs 26/27, right?

> I think this is an unfair diff,how can we tell different from this too markup?and which one should be apply on another one?
> ```html
<p></p>
    <p><i></i>
    </p>
    <p></p><i><img><span><b></b></span><img></i>
    <p></p><i><img><span></span></i>
    <p><i></i>
    </p>
    <p></p>
    <img><span><span></span></span>
    <img>
```
```html
    <img><i></i>
    <p><span><span><b></b></span></span>
    </p>
    <p></p><b><img><span></span></b>
    <p><b></b>
    </p>
    <p></p>
    <p></p>
    <p>wg</p><i><p></p></i>2nJ<i><img></i>
    <p></p><i><img></i>zV87J1UU3Ex
```


Is your complaint about the size of these? Well, as I said earlier, you need to shrink them down by removing individual elements with the bug not disappearing. I have done that for you and put them at the top of basic.html. The two are now these:

```
<div><p></p><p></p><img></div>
<div><img><p></p></div>
```

I will log off now. I hope I gave you enough pointers now so that you can start working on this yourself.

**Comment by unbug** [comment]
@johanneswilm Thanks for the point out.
I've debug in the apply function,I think the issue may cause by the ```getFromRoute```,but it reminds me actually the old version some time has issue too,when I apply the levelsDeep,some time its has this problem on mobile safari,I event creat a demo for [virtual-dom](https://github.com/Matt-Esch/virtual-dom/blob/master/vdom/README.md),turns out,it's diff function event got more issues,this is maybe a clue for the diff arithmetic,I am still digging,
```
var vdom = require("virtual-dom");//https://github.com/Matt-Esch/virtual-dom
var html2hscript = require('html2hscript');//https://github.com/twilson63/html2hscript

module.exports = window.converterX = function initializeConverter (rootNode,newHtml) {
    var nNode = rootNode.cloneNode(),otree,ntree,diffRs;
    nNode.innerHTML = newHtml;
    html2hscript(rootNode.outerHTML, function(err, ohscript) {
        otree = ohscript;
        html2hscript(nNode.outerHTML, function(err, nhscript) {
            ntree = nhscript;
            diffRs = vdom.diff(otree,ntree);
            console.log(vdom.createElement(otree),vdom.createElement(ntree),diffRs);
            vdom.patch(rootNode,diffRs);
        });
    });
};
```
I got emergency team work to handle,I'll get back to the test ASAP,sorry about this.

**Comment by johanneswilm** [comment]
@unbug + @episodeyang: I have created a 1.9.0 (pre)release based on the new code. It also includes a mechanism to seek only down to a certain level and a lot of things are actually better than in the 1.2.0 version -- the last with the old DOM handling. But nevertheless, a lot of bugs can still be found, and it won't be ready for a 2.0 release before those are addressed. Unfortunately I have run out of time to work on this for now. There is a test included which lets you try to "mine" for bugs. SO if you want to use it -- feel free to do that.

**Comment by unbug** [comment]
I'll put it in real world use,thanks man :)

**Comment by unbug** [comment]
@johanneswilm I cant find the maxDEpath option in the latest codes any more,it's it be removed?

**Comment by johanneswilm** [comment]
@unbug still there. nothing has changed. https://github.com/fiduswriter/diffDOM/blob/gh-pages/diffDOM.js#L511

**Comment by unbug** [comment]
@johanneswilm Now I got more time to work on the test,do you have any new test guide for me?More clue more better.
I should apply the new codes to me project.

**Comment by johanneswilm** [comment]
@unbug No, but just leave the "random unlimited" test [1] running for about 20 minutes. It sill "find" some bug for you. :)

[1] http://fiduswriter.github.io/diffDOM/tests/random-unlimited.html

**Comment by unbug** [comment]
@johanneswilm  OK,I am applying the new codes to my project,and I'll read the new codes to see if there any thing I can help :)

**Comment by unbug** [comment]
@johanneswilm When it's match the maxDepth,all the child node should be replace,the diffDOM just skip them,so the new DOM always be the same as the new HTML.
E.g. maxDepth is 2
```
<div class="root">
  <div class="d1">
        <div class="d2">
            <div class="d3">
                    I an mew,please don't skip me.
             </div>
        </div>
  </div>
</div>
```

Should I open a new issue for this?

**Comment by johanneswilm** [comment]
Ah, yes that would be quite a different feature. How do you you know whether or not to a second level node needs to be exchanged if you don't diff it? Do you simply add diffs for all second level nodes? The easiest would probably be if you simply remove anything beyond the second level in t1 and then diff that against a full t2. You are welcome to try to write a patch and create a PR.

**Comment by unbug** [comment]
@johanneswilm Hum...are you define the maxDepth's behaviour like what it is now,or should I use another attribute name?

**Comment by johanneswilm** [comment]
Start with another attribute. It may turn out not to be possible at all, or zero savings in time. Or it may turn out to make sense, then we can adjust the names. The thing you implemented last time had the same effect as what maxDepth does now.

**Comment by unbug** [comment]
@johanneswilm I'll work on it tonight,do you got any clue for me to make it quick?Or something I should not touch?

**Comment by johanneswilm** [comment]
Keep all the config oprions in the diffDom options array. Other than that, I don't think there is anything.

**Comment by johanneswilm** [comment]
@unbug last change gives a speed increase of about factor 4-5. So it's down to 400-700 milliseconds for your example file that used to take 27 seconds.

**Comment by unbug** [comment]
@johanneswilm this is cool,and it is hard to make a levels deep now,I am still digging.

**Comment by unbug** [comment]
@johanneswilm I've apply the new version to my project,for now everything looks very OK,I'll keep watching if there is any new bug comes up.
This is [a plugin for jQuery&zepto](https://github.com/unbug/generator-webappstarter/blob/master/app/templates/app/src/util/VirtualDOMLite.js) base diffDOM.
