### ISSUE TITLE
Sub diffs

### ISSUE THREAD

**Issue by oliverfoster** [fiduswriter/diffDOM#34]
It'd be nice to be able to stop diffing at a node. Would allow for nested diffDOMs / views.

Was thinking of something like ```sync="false"``` although perhaps definable?

Below works:
```
nodeToObj: function(node) {
            var objNode = {}, dobj = this;
            objNode.nodeName = node.nodeName;
            if (objNode.nodeName === '#text' || objNode.nodeName === '#comment') {
                objNode.data = node.data;
            } else {
                if (node.attributes && node.attributes.length > 0) {
                    objNode.attributes = {};
                    Array.prototype.slice.call(node.attributes).forEach(
                        function(attribute) {
                            objNode.attributes[attribute.name] = attribute.value;
                        }
                    );
                    if (objNode.attributes['sync'] === "false") objNode.sync = false;
                }
                if (node.childNodes && node.childNodes.length > 0 && objNode.sync !== false) {
                    objNode.childNodes = [];
                    Array.prototype.slice.call(node.childNodes).forEach(
                        function(childNode) {
                            objNode.childNodes.push(dobj.nodeToObj(childNode));
                        }
                    );
                }
                if (this.valueDiffing) {
                    if (node.value) {
                        objNode.value = node.value;
                    }
                    if (node.checked) {
                        objNode.checked = node.checked;
                    }
                    if (node.selected) {
                        objNode.selected = node.selected;
                    }
                }
            }

            return objNode;
        },

```

What do you think?

**Comment by johanneswilm** [comment]
@oliverfoster hmm, yes, but what if someone happens to need an attribute called "sync"? Could you make the name of the attribute user definable and then create a PR?

**Comment by fabricekabongo** [comment]
:+1:

**Comment by oliverfoster** [comment]
Sorry guys, I needed a load of other stuff as well, and quite quickly. 

I back-ported your code to ie8 and was using it to do kinda React-Style model:change>view>template:rerender>domdiff>diffapply thing with Backbone and Handlebars to get rid of all my DOM manipulation code. (For which it works really well!! I like it a lot!).

However, I'm working on a project that requires a high level of accessibility, is already quite mature, needs ie8 support with jQuery, yadda-yadda, so it has been quicker for me to completely rewrite diffDOM into DOMDiffer to suit my needs a bit more.

I want to say a firm and sincere thank you for the awesomeness of your code and for the inspiration.
https://github.com/oliverfoster/DOMDiffer < here's my version if you fancy a gander.

Ollie.

**Comment by johanneswilm** [comment]
Cool! Did you include the licence info of you lib anywhere?

**Comment by oliverfoster** [comment]
Call it .. GPL-3? I'll put a package json in later today.
