### ISSUE TITLE
Do not package the `venv` dir (reduce the installed size 200x)

### ISSUE THREAD

**Issue by ChALkeR** [fiduswriter/diffDOM#35]
Your current npm package size is **33 MiB**, and unpacked size is **168 MiB** (as of `diff-dom@2.0.0`).

*167 MiB* of that is inside the `venv` directory.

It looks like stuff from that directory is not used by the package, so most probably it was packaged by an accident.

You could add it to `.npmignore` (if you have an `.npmignore` already) or to `.gitignore` (if you don't have an `.npmignore`), or use the [files](https://docs.npmjs.com/files/package.json#files) field in your `package.json` file.

--

Directory listing with sizes:
```
4,0K    diff-dom-2.0.0.tgz/bower.json
8,0K    diff-dom-2.0.0.tgz/demo
48K     diff-dom-2.0.0.tgz/diffDOM1.js
48K     diff-dom-2.0.0.tgz/diffDOM2.js
48K     diff-dom-2.0.0.tgz/diffDOM.js
4,0K    diff-dom-2.0.0.tgz/index.html
8,0K    diff-dom-2.0.0.tgz/LICENSE.txt
40K     diff-dom-2.0.0.tgz/newDiffDOM.js
28K     diff-dom-2.0.0.tgz/oldDiffDOM.js
4,0K    diff-dom-2.0.0.tgz/package.json
4,0K    diff-dom-2.0.0.tgz/README.md
40K     diff-dom-2.0.0.tgz/RecentDiffDOM.js
4,0K    diff-dom-2.0.0.tgz/test3.html
156K    diff-dom-2.0.0.tgz/test.html
296K    diff-dom-2.0.0.tgz/tests
167M    diff-dom-2.0.0.tgz/venv
```

**Comment by ChALkeR** [comment]
Ref: https://github.com/nodejs/node/pull/5230#issuecomment-186775054

**Comment by ChALkeR** [comment]
Things like `diffDOM1.js`, `diffDOM2.js`, `newDiffDOM.js`, `oldDiffDOM.js`, `RecentDiffDOM.js` also look a bit out of place.

**Comment by johanneswilm** [comment]
@ChALkeR Thanks for pointing that out. I just assumed it would only take the git-controlled files. I have removed the files and added the .gitignore file in the 2.0.1 release.
