### ISSUE TITLE
Modular compatibility

### ISSUE THREAD

**Issue by Announcement** [fiduswriter/diffDOM#44]
It shouldn't be hard, I'll provide a pull request if you want, but I came across a situation where I'm loading about five separate javascripts and figured it's time for AMD.js to handle it at this point.

> jQuery, diffDOM, socket.io, **responsive.js** ,*\* **patch.js**
> 
> **responsive.js** is a script a wrote to handle some ui events.
> **patch.js** listens to a node.js/socket.io server dispatching fs.watch file change events, applying html patches with diffDOM via AJAX/DOMParser.

Anyways, can you add AMD.js support or is that out of the question?

**Comment by johanneswilm** [comment]
Hey,
if this can be done in a way that's not being a problem to users of other solutions, I'm ok with adding support for that as well. Our main application has been converted to ES6 and uses the module support of that. The main reason diffDOM hasn't been converted to that is so it's not getting any more difficult for others to add to their solutions.

**Comment by johanneswilm** [comment]
@Announcement Are you still interested in providing this PR?

**Comment by johanneswilm** [comment]
This has been incorporated through a different patch.
