### ISSUE TITLE
Elements with matching IDs or classes are not matched more strongly

### ISSUE THREAD

**Issue by edg2s** [fiduswriter/diffDOM#49]
Although there is special code for creating identifiers based on ID or class, they don't change the behaviour of findCommonSubsets, as roughlyEqual gives the same result (true) for comparing `<p id="foo">` with `<p id="foo">` as it does `<p id="foo">` with `<p id="bar">`.

The result is changing a document from

`<p id="A"></p><p id="B"></p><p id="C"></p>` to `<p id="A"></p><p id="C"></p>`

results in an overly complicated diff of

```
{"action":"removeElement","route":[0],"element":{"nodeName":"P","attributes":{"id":"A"}}},
{"action":"modifyAttribute","route":[0],"name":"id","oldValue":"B","newValue":"A"}
```

**Comment by johanneswilm** [comment]
Hmm, thinking about writing a patch for this?

**Comment by Charuru** [comment]
@johanneswilm Are you taking this on? It's a pretty important issue for me.

**Comment by johanneswilm** [comment]
@Charuru We are generally happy with diffDOM as it is. But we'd be happy to merge a patch for this.

**Comment by johanneswilm** [comment]
This has been added in 2.3.0
