### ISSUE TITLE
Deep freeze on generating diff from specific data

### ISSUE THREAD

**Issue by vatavale** [fiduswriter/diffDOM#64]
Looks like it's connected with amount of mixed (moved) ids. And looks like there is a nonlinear dependence somewhere in the algorithm.
This is two fragments (it is different sorting of the same rows):

Element 1
`<ul><li id="ob987"></li><li id="ob986"></li><li id="ob988"></li><li id="ob991"></li><li id="ob989"></li><li id="ob992"></li><li id="ob993"></li><li id="ob990"></li><li id="ob742"></li><li id="ob741"></li><li id="ob743"></li><li id="ob744"></li><li id="ob749"></li><li id="ob745"></li><li id="ob751"></li><li id="ob752"></li><li id="ob753"></li><li id="ob755"></li><li id="ob754"></li><li id="ob756"></li><li id="ob757"></li><li id="ob758"></li><li id="ob760"></li><li id="ob759"></li><li id="ob761"></li><li id="ob762"></li><li id="ob763"></li><li id="ob764"></li><li id="ob765"></li><li id="ob766"></li><li id="ob767"></li><li id="ob768"></li><li id="ob770"></li><li id="ob769"></li><li id="ob771"></li><li id="ob773"></li><li id="ob772"></li><li id="ob775"></li><li id="ob774"></li><li id="ob776"></li><li id="ob777"></li><li id="ob779"></li><li id="ob778"></li><li id="ob780"></li><li id="ob781"></li><li id="ob782"></li><li id="ob784"></li><li id="ob783"></li><li id="ob785"></li><li id="ob786"></li><li id="ob787"></li><li id="ob789"></li><li id="ob788"></li><li id="ob790"></li><li id="ob791"></li><li id="ob792"></li><li id="ob793"></li><li id="ob794"></li><li id="ob795"></li><li id="ob802"></li><li id="ob801"></li><li id="ob803"></li><li id="ob804"></li><li id="ob797"></li><li id="ob796"></li><li id="ob798"></li><li id="ob799"></li><li id="ob800"></li><li id="ob805"></li><li id="ob806"></li><li id="ob807"></li><li id="ob809"></li><li id="ob808"></li><li id="ob810"></li><li id="ob811"></li><li id="ob812"></li><li id="ob814"></li><li id="ob813"></li><li id="ob815"></li><li id="ob816"></li><li id="ob817"></li><li id="ob819"></li><li id="ob818"></li><li id="ob820"></li><li id="ob821"></li><li id="ob822"></li><li id="ob823"></li><li id="ob824"></li><li id="ob825"></li><li id="ob827"></li><li id="ob826"></li><li id="ob828"></li><li id="ob829"></li><li id="ob830"></li><li id="ob832"></li><li id="ob831"></li><li id="ob833"></li><li id="ob834"></li><li id="ob836"></li><li id="ob835"></li><li id="ob837"></li><li id="ob838"></li><li id="ob839"></li><li id="ob841"></li><li id="ob840"></li><li id="ob842"></li><li id="ob843"></li><li id="ob844"></li><li id="ob846"></li><li id="ob845"></li><li id="ob847"></li><li id="ob849"></li><li id="ob848"></li><li id="ob850"></li><li id="ob851"></li><li id="ob852"></li><li id="ob854"></li><li id="ob853"></li><li id="ob856"></li><li id="ob857"></li><li id="ob855"></li><li id="ob858"></li><li id="ob860"></li><li id="ob859"></li><li id="ob862"></li><li id="ob861"></li><li id="ob864"></li><li id="ob865"></li><li id="ob866"></li><li id="ob863"></li><li id="ob868"></li><li id="ob867"></li><li id="ob870"></li><li id="ob871"></li><li id="ob872"></li><li id="ob869"></li><li id="ob874"></li><li id="ob873"></li><li id="ob875"></li><li id="ob877"></li><li id="ob876"></li><li id="ob879"></li><li id="ob880"></li><li id="ob881"></li><li id="ob878"></li><li id="ob883"></li><li id="ob882"></li><li id="ob885"></li><li id="ob886"></li><li id="ob887"></li><li id="ob884"></li><li id="ob888"></li><li id="ob889"></li><li id="ob890"></li><li id="ob891"></li><li id="ob892"></li><li id="ob894"></li><li id="ob895"></li><li id="ob893"></li><li id="ob897"></li><li id="ob896"></li><li id="ob900"></li><li id="ob898"></li><li id="ob899"></li><li id="ob901"></li><li id="ob903"></li><li id="ob902"></li><li id="ob905"></li><li id="ob906"></li><li id="ob904"></li><li id="ob907"></li><li id="ob909"></li><li id="ob910"></li><li id="ob908"></li><li id="ob912"></li><li id="ob911"></li><li id="ob914"></li><li id="ob915"></li><li id="ob916"></li><li id="ob913"></li><li id="ob918"></li><li id="ob917"></li><li id="ob920"></li><li id="ob921"></li><li id="ob922"></li><li id="ob919"></li><li id="ob924"></li><li id="ob923"></li><li id="ob926"></li><li id="ob927"></li><li id="ob928"></li><li id="ob925"></li><li id="ob930"></li><li id="ob929"></li><li id="ob932"></li><li id="ob933"></li><li id="ob934"></li><li id="ob931"></li><li id="ob936"></li><li id="ob935"></li><li id="ob937"></li><li id="ob938"></li><li id="ob940"></li><li id="ob939"></li><li id="ob941"></li><li id="ob942"></li><li id="ob944"></li><li id="ob943"></li><li id="ob946"></li><li id="ob947"></li><li id="ob948"></li><li id="ob945"></li><li id="ob950"></li><li id="ob949"></li><li id="ob952"></li><li id="ob953"></li><li id="ob954"></li><li id="ob951"></li><li id="ob956"></li><li id="ob955"></li><li id="ob958"></li><li id="ob959"></li><li id="ob960"></li><li id="ob957"></li><li id="ob961"></li><li id="ob962"></li><li id="ob964"></li><li id="ob963"></li><li id="ob965"></li><li id="ob966"></li><li id="ob967"></li><li id="ob968"></li><li id="ob970"></li><li id="ob969"></li><li id="ob971"></li><li id="ob974"></li><li id="ob972"></li><li id="ob975"></li><li id="ob976"></li><li id="ob973"></li><li id="ob977"></li><li id="ob978"></li><li id="ob979"></li><li id="ob981"></li><li id="ob980"></li><li id="ob982"></li><li id="ob983"></li><li id="ob984"></li><li id="ob985"></li><li id="ob995"></li><li id="ob994"></li><li id="ob996"></li><li id="ob997"></li><li id="ob998"></li><li id="ob999"></li><li id="ob1001"></li><li id="ob1000"></li><li id="ob1002"></li><li id="ob1003"></li><li id="ob1004"></li><li id="ob1005"></li><li id="ob1007"></li><li id="ob1006"></li><li id="ob1008"></li><li id="ob1009"></li><li id="ob1011"></li><li id="ob1010"></li><li id="ob1013"></li><li id="ob1012"></li><li id="ob1015"></li><li id="ob1014"></li><li id="ob1016"></li><li id="ob1017"></li><li id="ob1019"></li><li id="ob1018"></li><li id="ob1021"></li><li id="ob1020"></li><li id="ob1023"></li><li id="ob1022"></li><li id="ob1024"></li><li id="ob1025"></li><li id="ob1026"></li><li id="ob1027"></li><li id="ob1029"></li><li id="ob1028"></li><li id="ob1030"></li><li id="ob1031"></li><li id="ob1032"></li><li id="ob1033"></li><li id="ob1034"></li><li id="ob1035"></li><li id="ob1036"></li><li id="ob1038"></li><li id="ob1037"></li><li id="ob1040"></li><li id="ob1039"></li><li id="ob1041"></li><li id="ob1042"></li><li id="ob1043"></li><li id="ob1045"></li><li id="ob1046"></li><li id="ob1044"></li><li id="ob1048"></li><li id="ob1047"></li><li id="ob1053"></li><li id="ob1049"></li><li id="ob1050"></li><li id="ob1052"></li><li id="ob1051"></li><li id="ob1054"></li><li id="ob1059"></li><li id="ob1055"></li><li id="ob1056"></li><li id="ob1057"></li><li id="ob1058"></li><li id="ob1061"></li><li id="ob1060"></li><li id="ob1068"></li><li id="ob1062"></li><li id="ob1063"></li><li id="ob1064"></li><li id="ob1066"></li><li id="ob1067"></li><li id="ob1065"></li><li id="ob1070"></li><li id="ob1069"></li><li id="ob1076"></li><li id="ob1071"></li><li id="ob1072"></li><li id="ob1073"></li><li id="ob1075"></li><li id="ob1077"></li><li id="ob1074"></li><li id="ob1078"></li><li id="ob1079"></li><li id="ob1080"></li><li id="ob1081"></li><li id="ob1083"></li><li id="ob1084"></li><li id="ob1082"></li><li id="ob1086"></li><li id="ob1085"></li><li id="ob1087"></li><li id="ob1088"></li><li id="ob1089"></li><li id="ob1091"></li><li id="ob1092"></li><li id="ob1090"></li><li id="ob1093"></li><li id="ob1094"></li><li id="ob1095"></li><li id="ob1096"></li><li id="ob1097"></li><li id="ob1099"></li><li id="ob1098"></li><li id="ob1100"></li><li id="ob1101"></li><li id="ob1102"></li><li id="ob1104"></li><li id="ob1105"></li><li id="ob1103"></li><li id="ob1106"></li><li id="ob1107"></li><li id="ob1108"></li><li id="ob1109"></li><li id="ob1111"></li><li id="ob1110"></li></ul>`

Element 2
`<ul><li id="ob745"></li><li id="ob744"></li><li id="ob758"></li><li id="ob741"></li><li id="ob754"></li><li id="ob756"></li><li id="ob757"></li><li id="ob761"></li><li id="ob755"></li><li id="ob759"></li><li id="ob763"></li><li id="ob767"></li><li id="ob768"></li><li id="ob766"></li><li id="ob774"></li><li id="ob769"></li><li id="ob743"></li><li id="ob762"></li><li id="ob742"></li><li id="ob760"></li><li id="ob778"></li><li id="ob783"></li><li id="ob788"></li><li id="ob764"></li><li id="ob780"></li><li id="ob785"></li><li id="ob753"></li><li id="ob765"></li><li id="ob792"></li><li id="ob796"></li><li id="ob776"></li><li id="ob777"></li><li id="ob775"></li><li id="ob801"></li><li id="ob805"></li><li id="ob771"></li><li id="ob781"></li><li id="ob808"></li><li id="ob790"></li><li id="ob803"></li><li id="ob798"></li><li id="ob810"></li><li id="ob791"></li><li id="ob795"></li><li id="ob751"></li><li id="ob752"></li><li id="ob749"></li><li id="ob773"></li><li id="ob772"></li><li id="ob770"></li><li id="ob813"></li><li id="ob818"></li><li id="ob834"></li><li id="ob831"></li><li id="ob833"></li><li id="ob832"></li><li id="ob823"></li><li id="ob800"></li><li id="ob807"></li><li id="ob789"></li><li id="ob797"></li><li id="ob793"></li><li id="ob804"></li><li id="ob782"></li><li id="ob825"></li><li id="ob779"></li><li id="ob802"></li><li id="ob835"></li><li id="ob784"></li><li id="ob786"></li><li id="ob840"></li><li id="ob787"></li><li id="ob817"></li><li id="ob814"></li><li id="ob845"></li><li id="ob848"></li><li id="ob847"></li><li id="ob846"></li><li id="ob853"></li><li id="ob815"></li><li id="ob820"></li><li id="ob824"></li><li id="ob858"></li><li id="ob816"></li><li id="ob859"></li><li id="ob794"></li><li id="ob799"></li><li id="ob806"></li><li id="ob811"></li><li id="ob828"></li><li id="ob837"></li><li id="ob812"></li><li id="ob809"></li><li id="ob826"></li><li id="ob861"></li><li id="ob842"></li><li id="ob850"></li><li id="ob856"></li><li id="ob860"></li><li id="ob857"></li><li id="ob855"></li><li id="ob854"></li><li id="ob867"></li><li id="ob870"></li><li id="ob882"></li><li id="ob865"></li><li id="ob871"></li><li id="ob886"></li><li id="ob887"></li><li id="ob864"></li><li id="ob885"></li><li id="ob873"></li><li id="ob838"></li><li id="ob839"></li><li id="ob836"></li><li id="ob876"></li><li id="ob829"></li><li id="ob880"></li><li id="ob830"></li><li id="ob827"></li><li id="ob879"></li><li id="ob851"></li><li id="ob852"></li><li id="ob849"></li><li id="ob895"></li><li id="ob893"></li><li id="ob892"></li><li id="ob898"></li><li id="ob896"></li><li id="ob843"></li><li id="ob844"></li><li id="ob894"></li><li id="ob841"></li><li id="ob900"></li><li id="ob875"></li><li id="ob874"></li><li id="ob902"></li><li id="ob907"></li><li id="ob821"></li><li id="ob822"></li><li id="ob904"></li><li id="ob908"></li><li id="ob909"></li><li id="ob819"></li><li id="ob872"></li><li id="ob869"></li><li id="ob868"></li><li id="ob888"></li><li id="ob890"></li><li id="ob891"></li><li id="ob866"></li><li id="ob863"></li><li id="ob862"></li><li id="ob889"></li><li id="ob911"></li><li id="ob917"></li><li id="ob905"></li><li id="ob914"></li><li id="ob920"></li><li id="ob906"></li><li id="ob910"></li><li id="ob915"></li><li id="ob921"></li><li id="ob923"></li><li id="ob926"></li><li id="ob929"></li><li id="ob932"></li><li id="ob901"></li><li id="ob935"></li><li id="ob899"></li><li id="ob927"></li><li id="ob933"></li><li id="ob897"></li><li id="ob883"></li><li id="ob912"></li><li id="ob916"></li><li id="ob884"></li><li id="ob913"></li><li id="ob940"></li><li id="ob939"></li><li id="ob941"></li><li id="ob938"></li><li id="ob946"></li><li id="ob947"></li><li id="ob943"></li><li id="ob953"></li><li id="ob959"></li><li id="ob952"></li><li id="ob958"></li><li id="ob965"></li><li id="ob949"></li><li id="ob955"></li><li id="ob963"></li><li id="ob928"></li><li id="ob925"></li><li id="ob903"></li><li id="ob924"></li><li id="ob881"></li><li id="ob878"></li><li id="ob877"></li><li id="ob961"></li><li id="ob934"></li><li id="ob931"></li><li id="ob930"></li><li id="ob991"></li><li id="ob974"></li><li id="ob972"></li><li id="ob988"></li><li id="ob971"></li><li id="ob969"></li><li id="ob986"></li><li id="ob978"></li><li id="ob979"></li><li id="ob977"></li><li id="ob980"></li><li id="ob997"></li><li id="ob996"></li><li id="ob994"></li><li id="ob983"></li><li id="ob982"></li><li id="ob962"></li><li id="ob1002"></li><li id="ob1000"></li><li id="ob948"></li><li id="ob989"></li><li id="ob945"></li><li id="ob944"></li><li id="ob1006"></li><li id="ob1003"></li><li id="ob1009"></li><li id="ob1017"></li><li id="ob1014"></li><li id="ob1024"></li><li id="ob1022"></li><li id="ob918"></li><li id="ob942"></li><li id="ob1025"></li><li id="ob922"></li><li id="ob919"></li><li id="ob1008"></li><li id="ob1016"></li><li id="ob1028"></li><li id="ob1011"></li><li id="ob957"></li><li id="ob960"></li><li id="ob1031"></li><li id="ob956"></li><li id="ob1034"></li><li id="ob1019"></li><li id="ob1039"></li><li id="ob990"></li><li id="ob973"></li><li id="ob999"></li><li id="ob995"></li><li id="ob1030"></li><li id="ob1035"></li><li id="ob1047"></li><li id="ob1036"></li><li id="ob1041"></li><li id="ob1049"></li><li id="ob1055"></li><li id="ob1054"></li><li id="ob1042"></li><li id="ob1050"></li><li id="ob1056"></li><li id="ob966"></li><li id="ob1057"></li><li id="ob1043"></li><li id="ob1106"></li><li id="ob992"></li><li id="ob998"></li><li id="ob993"></li><li id="ob987"></li><li id="ob1060"></li><li id="ob1069"></li><li id="ob1062"></li><li id="ob1071"></li><li id="ob1063"></li><li id="ob1072"></li><li id="ob1078"></li><li id="ob1085"></li><li id="ob1064"></li><li id="ob1073"></li><li id="ob1079"></li><li id="ob1093"></li><li id="ob1098"></li><li id="ob967"></li><li id="ob968"></li><li id="ob964"></li><li id="ob1087"></li><li id="ob1094"></li><li id="ob1080"></li><li id="ob975"></li><li id="ob976"></li><li id="ob970"></li><li id="ob1095"></li><li id="ob1032"></li><li id="ob1033"></li><li id="ob1029"></li><li id="ob1044"></li><li id="ob937"></li><li id="ob1088"></li><li id="ob1081"></li><li id="ob936"></li><li id="ob1089"></li><li id="ob1096"></li><li id="ob1048"></li><li id="ob1038"></li><li id="ob1107"></li><li id="ob1053"></li><li id="ob1020"></li><li id="ob1051"></li><li id="ob1108"></li><li id="ob954"></li><li id="ob1045"></li><li id="ob951"></li><li id="ob1046"></li><li id="ob950"></li><li id="ob1040"></li><li id="ob1102"></li><li id="ob1100"></li><li id="ob1023"></li><li id="ob1026"></li><li id="ob1090"></li><li id="ob1018"></li><li id="ob1021"></li><li id="ob1027"></li><li id="ob1015"></li><li id="ob1101"></li><li id="ob1037"></li><li id="ob1103"></li><li id="ob1104"></li><li id="ob1105"></li><li id="ob1099"></li><li id="ob1012"></li><li id="ob1091"></li><li id="ob1092"></li><li id="ob1086"></li><li id="ob1067"></li><li id="ob1061"></li><li id="ob1109"></li><li id="ob1007"></li><li id="ob1065"></li><li id="ob1010"></li><li id="ob1013"></li><li id="ob1074"></li><li id="ob1059"></li><li id="ob1068"></li><li id="ob1005"></li><li id="ob1001"></li><li id="ob1004"></li><li id="ob1077"></li><li id="ob1084"></li><li id="ob1070"></li><li id="ob1052"></li><li id="ob1066"></li><li id="ob1075"></li><li id="ob1083"></li><li id="ob1076"></li><li id="ob1058"></li><li id="ob1110"></li><li id="ob1097"></li><li id="ob1082"></li><li id="ob985"></li><li id="ob984"></li><li id="ob981"></li><li id="ob1111"></li></ul>`

**Comment by vatavale** [comment]
Maybe it will be easier to replace whole parent node, if complexity of changes in child nodes is more than some limit?

**Comment by johanneswilm** [comment]
@vatavale take a look at my proposed solution. I have added your example as the long-list test with a `maxChildCount` setting. Would that work for you?

**Comment by vatavale** [comment]
Yes it works good for me! Well done! And thank you for such a great tool!

**Comment by johanneswilm** [comment]
@vatavale Great. I also tried to look more at the original issue and I started a branch where subtree maps are cached for every 100 diffs [1]. Unfortunately, that still does not give a full result even with a diffcap of 10000. While it does progress, it seems like there are a lot of circular diffs there. Probably something that could be optimized. I don't think I have time to do that, but someone probably should some day.

[1] https://github.com/fiduswriter/diffDOM/tree/cache-subtree-maps

**Comment by vatavale** [comment]
With `maxChildCount` and `maxChildCountDiffCount` setted to small numeral, sometimes there are errors.
For example, with diffing of this two fragments and child counts = 1:
```
<div><ul data-gid="10"><li data-id="631"></li></ul><br><br><br></div>
<div><ul data-gid="14"><li data-id="644"></li></ul><br><br><br></div>
```
`Cannot read property 'childNodes' of undefined`

Looks like it is connected with repeated `<br>` tag.
