### ISSUE TITLE
Cannot read property 'childNodes' of undefined

### ISSUE THREAD

**Issue by vatavale** [fiduswriter/diffDOM#67]
With `maxChildCount` and `maxChildCountDiffCount` setted to small numeral, sometimes there are errors.
For example, with diffing of this two fragments and child counts = 1:

```
<div><ul data-gid="10"><li data-id="631"></li></ul><br><br><br></div>
<div><ul data-gid="14"><li data-id="644"></li></ul><br><br><br></div>
```
Eror `Cannot read property 'childNodes' of undefined`.
Looks like it is connected with repeated `<br>` tag.

Without `maxChildCount` it works good.

**Comment by johanneswilm** [comment]
Hey @vatavale , I found the issue. It's when the top node you send in to diff has a bunch of children. Then it tried to replace that top node, and because there isn't any way you can diff one element and replace it entirely with a different one if it has no parentElement, it threw an error. 

For now I've set it to only use maxChildCount in non-top nodes, but we may need another solution. You are welcome to send in a patch proposal.

Also notice, I changed maxChildCountDiffCount to maxChildDiffCount.

**Comment by vatavale** [comment]
Ok. I see now.
The solution had solved problem for me.
Thank you so much!

**Comment by vatavale** [comment]
Some new patterns causing **different** errors (**even with** maxChildCount: false)

```php
var a = '<div></div>';
var b = '<div><strong>1</strong></div>';
// TypeError: Cannot read property '0' of undefined

var a = '<div><br><br></div>';
var b = '<div><br></div>';
// TypeError: Cannot read property 'removeChild' of undefined

var a = '<br><br>';
var b = '<br>';
// TypeError: Cannot read property 'childNodes' of undefined
```
And this is interesting:
```php
var a = '<div></div><div></div>';
var b = '<div></div>';
// **Is OK**
        
var a = '<strong></strong><strong></strong>';
var b = '<strong></strong>';
// Cannot read property 'childNodes' of undefined
       
```

**Comment by marcelpanse** [comment]
@vatavale did you find a solution yet?

**Comment by johanneswilm** [comment]
@marcelpanse I will take a quick look this morning. In general I am not opposed to others trying to come up with fixes as well. :)

**Comment by marcelpanse** [comment]
I was just wondering if this was still an issue. I just tried to reproduce it, but can't.

**Comment by johanneswilm** [comment]
Same here. I cannot reproduce these. @vatavale Could you check if these are still broken for you?

**Comment by johanneswilm** [comment]
Looks like it's fixed. Please reopen if not.
