### ISSUE TITLE
Simple diff gives 100s of redundant addElement/removeElement diffs

### ISSUE THREAD

**Issue by rweigel** [fiduswriter/diffDOM#69]
Exellent library. Using it to develop math editor that re-renders only changed nodes.

The following gives 3 diffs for the first diff and 203 for the second diff. Using diffDOM from repository two days ago.
```
<head>
  <meta charset="utf-8">
  <title>diffDOM</title>
  <script src="diffDOM/diffDOM.js"></script>
 </head>
<body>
  <div id="diffDOM"><span>a</span><span>b</span></div>
  <div id="diffDOM"><span>a</span>b</div>
</body>
<script>
  var el1  = document.querySelectorAll('#diffDOM')[0];
  var el2  = document.querySelectorAll('#diffDOM')[1];
  var dd = new diffDOM();
  var d = dd.diff(el1, el2);
  console.log(d)
  var d = dd.diff(el2, el1);
  console.log(d)
 </script>
```

**Comment by marcelpanse** [comment]
I have a similar problem. See this simple fiddle: 
https://jsfiddle.net/znxhvLvx/

It has something to do with the unwrapped textnodes, any idea what is happening / how to fix it?

**Comment by johanneswilm** [comment]
Issue does not seem to be present in last release, version 2.3.1. Please use a release if you run code in production level environment. Thanks for reporting, I'll try to make sure it's removed before release of the next version.

**Comment by marcelpanse** [comment]
@johanneswilm That seems correct, the issue does not occur in 2.3.1, but does in the latest dev version and the version used in the demo pages online (which I used for the fiddle).

I'll do some more testing with the 2.3.1 version

**Comment by johanneswilm** [comment]
@marcelpanse I didn't actually get to see your test case before I resolved this. I can see that you have about 7 diffs and no errors. That seems about right.

**Comment by marcelpanse** [comment]
Yes, it seems fixed now. I guess you updated https://fiduswriter.github.io/diffDOM/diffDOM.js with the new code. Before it would give 300+ diffs.

**Comment by johanneswilm** [comment]
Yes, that's the current dev version. Please don't link to that URL in production.

But given that you guys now tested the test version and we fixed the only issue you have found so far, maybe we are ready for a new production version.

**Comment by johanneswilm** [comment]
Ok, thanks! I'll try to be more responsive during the next two weeks.
