### ISSUE TITLE
Route Incorrect For Removals (Multiple Distinct Elements Have Same Route)

### ISSUE THREAD

**Issue by benorgera** [fiduswriter/diffDOM#70]
My understanding of the route attribute of a diff object is that it can be used to retrieve the original element that was modified. For removals, this element lives in the first dom, and for additions/modifications, it lives in the second. So given:

```
const { DOMParser, XMLSerializer } = require('xmldom')
        , p = new DOMParser()
        , domBefore = p.parseFromString(xmlBefore)
        , domAfter = p.parseFromString(xmlAfter)
        , diff = dd.diff(domBefore, domAfter);
```

We should have the invariant that for every element `d` of `diff`, `dd.getFromRoute(d.action.includes('remove') ? domBefore : domAfter, d.route)` is the same element as `d.element`.

However sometimes the last element of route is incorrect, breaking this invariant. Given `xmlBefore` of:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE assessment>
<assessment>
  <title>Test</title>
  <short_title>Test</short_title>
  <page>
    <title>Page 1</title>
    <question>
      <multiple_choice shuffle="true" select="multiple" labels="false">
        <choice value="A">Placeholder</choice>
        <choice value="B">Placeholder</choice>
      </multiple_choice>
      <part id="be03031c79464d08a5bce122fee68ffc">
        <response match="A" score="1">
          <feedback>
            <p id="aa3ab72153c834c8395a0099dff39d434"/>
          </feedback>
        </response>
        <response match="A,B" score="0" name="AUTOGEN_{A,B}">
          <feedback>
            <p id="ab8e552e886ee486baf47d45c778deac4"/>
          </feedback>
        </response>
        <response match="B" score="0" name="AUTOGEN_{B}">
          <feedback>
            <p id="aed5ccfa249794825a9fd6e05233ca5c1"/>
          </feedback>
        </response>
      </part>
    </question>
  </page>
</assessment>
```

and `xmlAfter` of:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE assessment>
<assessment>
  <title>Test</title>
  <short_title>Test</short_title>
  <page>
    <title>Page 1</title>
    <question>
      <multiple_choice shuffle="true" select="multiple" labels="false">
        <choice value="A">Placeholder</choice>
        <choice value="B">Placeholder</choice>
      </multiple_choice>
      <part id="be03031c79464d08a5bce122fee68ffc">
        <response match="A" score="1">
          <feedback>
            <p id="aa3ab72153c834c8395a0099dff39d434"/>
          </feedback>
        </response>
      </part>
    </question>
  </page>
</assessment>
```

`diff` is:
```
[ { action: 'removeTextElement',
    route: [ 4, 5, 3, 3, 0 ],
    value: '\r\n        ' },
  { action: 'removeElement',
    route: [ 4, 5, 3, 3, 0 ],
    element:
     { nodeName: 'response',
       attributes: [Object],
       childNodes: [Array] } },
  { action: 'removeTextElement',
    route: [ 4, 5, 3, 3, 0 ],
    value: '\r\n        ' },
  { action: 'removeElement',
    route: [ 4, 5, 3, 3, 0 ],
    element:
     { nodeName: 'response',
       attributes: [Object],
       childNodes: [Array] } },
  { action: 'modifyAttribute',
    route: [ 4, 5, 3, 3, 1 ],
    name: 'match',
    oldValue: 'B',
    newValue: 'A' },
  { action: 'removeAttribute',
    route: [ 4, 5, 3, 3, 1 ],
    name: 'name',
    value: 'AUTOGEN_{B}' },
  { action: 'modifyAttribute',
    route: [ 4, 5, 3, 3, 1 ],
    name: 'score',
    oldValue: '0',
    newValue: '1' },
  { action: 'removeElement',
    route: [ 4, 5, 3, 3, 1, 1, 1 ],
    element: { nodeName: 'p', attributes: [Object] } },
  { action: 'addElement',
    route: [ 4, 5, 3, 3, 1, 1, 1 ],
    element: { nodeName: 'p', attributes: [Object] } } ]
```
All of the removed elements have the same route `[ 4, 5, 3, 3, 0 ]`. I think this bug is caused by lines 936 and 945 of diffDOM.js, where
```
diffs.push(new Diff()
    .setValue(t._const.action, t._const.removeTextElement)
    .setValue(t._const.route, route.concat(index2))
    .setValue(t._const.value, node.data)
);
```
should actually be doing `route.concat(index1)`. However I feel like this issue may exist elsewhere in the code where remove diff routes are handled. Can this be fixed so that the removal routes can be used to get dom elements from the first dom (domBefore)?

**Comment by vatavale** [comment]
@benorgera Do you have some progress in this issue? Looks like you have a good understanding of algorithm. Maybe you can propose a patch for testing?
The DiffDOM library is great, but looks like @johanneswilm have no time for farther development.

**Comment by johanneswilm** [comment]
@vatavale Right, I don't have time to develop new features that I don't have a usecase for myself (unless someone pays me to do it). But of course I am interested in fixing bugs. So if you guys can propose patches, I am very interested.

**Comment by johanneswilm** [comment]
@benorgera Are you sure there is a bug? The patches are applied in order and the route numbers describe their place after all previous patches have been applied. So in your case, `[ 4, 5, 3, 3, 0 ]` first corresponds to a text node. After that node has been removed, the same route description corresponds to a `<response>`-node. After that node has been removed, it corresponds to another text node, etc. .

Unless there is something more in this that I haven't quite understood from your report, I don't think there is a bug. I will therefore close this issue now. Please reopen in case I misunderstood you.
