### ISSUE TITLE
INPUT modifyAttribute does not affect value

### ISSUE THREAD

**Issue by martindrapeau** [fiduswriter/diffDOM#73]
When you apply this type of diff on an INPUT element, the value is not changed in the DOM.
```
{"action":"modifyAttribute","route":[1],"name":"value","oldValue":"hello","newValue":""}
```
Funny thing you diff again and apply again and you get this diff instead:
```
{"action":"modifyValue","oldValue":"hello","newValue":"","route":[1]}
```
Then the INPUT value changes in the DOM.

Load up this file in your browser and see for yourself.
https://gist.github.com/martindrapeau/097e21bea76362a0976386ad9c0c7326

**Comment by johanneswilm** [comment]
Modify attribute and modify value are not the same thing. I don't think I get what the issue is.

**Comment by martindrapeau** [comment]
The issue is the `modifyValue` action is not triggered when the value is changed from a diff.

**Comment by johanneswilm** [comment]
With your first diff you are only modifying the attribute while the value stays the same. Is that what you are seeing?

**Comment by martindrapeau** [comment]
Let me try to explain another way - I'd like to understand. First html is:
```
<input type="text" value="hello" />
```
I then change it to this:
```
<input type="text" value />
```
That gives me a `modifyAttribute` action.
I would expect the diff to give me a `modifyValue` action. The value did change - did it not?

**Comment by martindrapeau** [comment]
Ok, the difference between the attribute value and the value of the input has now sunk in.
It does feel like there is a bug though. My example again:
Existing markup in the DOM:
```
<input type="text" value="hello" />, value="hello"
```
New element just created from scratch:
```
<input type="text" value="" />, value=""
```
Diff both. Diff only gives the `modifyAttribute`. Should it not also give the `modifyValue`?

**Comment by martindrapeau** [comment]
In fact your first ["Input type = text" test ](https://github.com/fiduswriter/diffDOM/blob/gh-pages/tests/form.html#L240) is wrong. It expects only one diff but there should be two.
```

    <input type="text" value="textinput">
    <input type="text">
```
Consider the above. Both the attribute and value are different no?

**Comment by johanneswilm** [comment]
The issue seems to be that at one point, modifying the value of an element would not modify the value-attribute, but the other way around (modifying the value-attribute) would modify the value. So it's made to work like that: https://github.com/fiduswriter/diffDOM/blob/gh-pages/diffDOM.js#L1113-L1115

Now Chrome does not act like that any more, nor does Firefox. In the end these are the main use cases. I will remove this fix and hope it breaks no older browsers. I will make a new minor version number though, just because it could.

**Comment by johanneswilm** [comment]
changed in 2.5.0. Let me know if you find further issues, @martindrapeau
