### ISSUE TITLE
Preventing a `removeElement` action in `preDiffApply` is messing up diffs of an adjacent element.

### ISSUE THREAD

**Issue by blakemann** [fiduswriter/diffDOM#74]
Given the following markup:

```html
<div id="a">
    <div class="before"></div>
    <a href="#before">Before</a>
</div>

<div id="b">
    <span class="after"></span>
    <a href="#after">After</a>
</div>
```

I set up a simple scenario where I want to diff `#a` against `#b` and apply the diff to `#a`, but I have used the `preDiffApply` function to try to prevent removal of the `div` element:

```js
const a = document.querySelector('#a');
const b = document.querySelector('#b');

const differ = new diffDOM({
    preDiffApply: function(info){
        if(info.diff.action === 'removeElement' && info.node.nodeName === 'DIV' && info.node.classList.contains('before')){
            return true;
        }
    }
});

const diff = differ.diff(a, b);
differ.apply(a, diff);
```

I would expect that because I have only prevented the `removeElement` action, that the `addElement` action for the `span` would still take place, as would the `modifyAttribute` and `modifyTextElement` actions which would update the `a` element, and the following output would be the result of what `#a` would become:

```html
<div id="b">
    <span class="after"></span>
    <div class="before"></div>
    <a href="#after">After</a>
</div>
```

However, the `modifyAttribute` and `modifyTextElement` actions are no longer performing correctly and the following output is the result instead:

```html
<div id="b">
    <span class="after"></span>
    <div class="before"></div>
    <a href="#before">Before</a> <!-- this node has not changed as expected -->
</div>
```

If I log the `info` variable in the function, It looks like the `modifyAttribute` action is still present, but is not referencing the correct node, and the `modifyTextElement` action is missing altogether.

<img width="601" alt="screen shot 2018-11-11 at 9 27 03 pm" src="https://user-images.githubusercontent.com/4955976/48326828-b409ee80-e5f8-11e8-954a-fd6cadcc621b.png">

Here is a full example file containing the code referenced in this issue:

[diff-test.html.zip](https://github.com/fiduswriter/diffDOM/files/2570549/diff-test.html.zip)

**Comment by johanneswilm** [comment]
Each diff step contains a path to the node that a change is being done on. If there are several steps, the path of later steps require all previous steps to have been applied first.  If you don't apply them like that, you need to adjust the steps in later steps yourself.

**Comment by blakemann** [comment]
@johanneswilm Could you provide an example of how I would adjust the later steps? I'm confused, as the node that is not being correctly diffed is not the node that I am preventing one of the actions for.

**Comment by johanneswilm** [comment]
The point is the route. If the route is something like [0, 2] then that means "pick the first child (0) of the element, then pick the third child (2) of that node and apply the action to that."

So if you prevented the deletion of the element at [0, 0] then all other operations that follow it with routes such as [0, 0], [0, 1] and [0, 2] will need to have their route adjusted to [0, 1], [0, 2] and [0, 3], whereas [1, 0], [2, 3], [3, 0], etc. all stay the same (only the ones at [0, x] are affected).
