### ISSUE TITLE
IE11 exception: possible typo

### ISSUE THREAD

**Issue by alexTayanovsky** [fiduswriter/diffDOM#75]
IE11 failed on the following line, so I'm curious if it's really meant to be an object, or plain `console.log(t1, t2)` is okay here?
https://github.com/fiduswriter/diffDOM/blob/855305ee28a0ed591dad577691a9b06d43cea0c0/diffDOM.js#L556

**Comment by johanneswilm** [comment]
It's not a typo, but possibly not allowed in older browsers.
