### ISSUE TITLE
filter outer diff

### ISSUE THREAD

**Issue by nkgsv** [fiduswriter/diffDOM#81]
What I'm trying to achieve is to consider nodes equal if they have equal value of the 'data-summary' attribute. In other words, for such nodes I would like to skip any inner diffs. Given the following DOM
```
<div id="txt1"><span data-summary="xxx">aaa</span></div>
<div id="txt2"><span data-summary="xxx">bbb</span></div>
```
after executing
```
var dd = new diffDOM.DiffDOM({
    filterOuterDiff: function(t1, t2, diffs) {
          if (!diffs.length && 'data-summary' in t1.attributes && t1.attributes['data-summary'] == t2.attributes['data-summary']) {
              t1.innerDone = true;
          }
    }
});
elementA = document.getElementById("txt1");
elementB = document.getElementById("txt2");
delta = dd.diff(elementA, elementB);
console.log(delta);
```
the following is what I get:

```
Array (2)
0 a {action: "modifyAttribute", route: [], name: "id", oldValue: "txt1", newValue: "txt2", …}
1 a {action: "modifyTextElement", route: [0, 0], oldValue: "aaa", newValue: "bbb", toString: function, …}
```

I am confused by the second element of `delta`, namely `modifyTextElement` in my opinion comes from the inner diff, which should have been skipped. Am I doing something wrong? Thanks!

**Comment by SqrTT** [comment]
in my case filterOterDiff is never called, because it comes in options but code here: https://github.com/fiduswriter/diffDOM/blob/gh-pages/src/diffDOM/virtual/diff.js#L77 is looking in `this`...

**Comment by SqrTT** [comment]
#82

**Comment by johanneswilm** [comment]
This has been merged.
