### ISSUE TITLE
diffDOM.js no longer in NPM package

### ISSUE THREAD

**Issue by tombye** [fiduswriter/diffDOM#84]
I recently updated from 2.3.1 to 3.1.0 and found the `diffDOM.js` file is no longer in the NPM package.

I'm been using `diffDOM.js` on the client-side, using NPM to get the diff-dom package and referencing the `diffDOM.js` file in my build. Now `diffDOM.js` isn't in the NPM package I've had to move to using the 3.1.0 release tarball to get it instead.

Is this the recommended approach or would it be possible to put the `/browser` back in the NPM package?

Thanks!

**Comment by johanneswilm** [comment]
@tombye Almost everyone will be using it in the browser. Only very recently did it start to make sense to use part of the package also in the backend. The "browser" file you found is for people who are not yet using npm. If you are using npm and a bundler, you don't need to specify which file to use - the package.json file takes care of describing where the default file is. 

Looking at those diffs of yours, it looks like you are doing something non-standard. If you want to find the file manually, look in the package.json file for "module" (this is the ES2015 source version of the code) and for "main" to find the bundled version (dist/index.js inside the npm package).

**Comment by mvorisek** [comment]
In our usecase we include the `browser/diffDOM.js` script in the browser, but when installed thru npm, the file is not present

when `browser/diffDOM.js` is replaced with `browser/dist/index.js`, it does not work as the file does not define the `diffDOM` variable

is there any way how to use/include the `browser/dist/index.js` directly in browser using `<script` tag?

**Comment by johanneswilm** [comment]
Hey @mvorisek, I don't fully get why you do it that way, but starting with diff-dom 4.2.7, the browser directory is exported to npm as well.

**Comment by mvorisek** [comment]
@johanneswilm thank you very much - in our usecase in atk4/ui we bundle the lib in git and in CI, we download the JS file using npm and assert it is unchanged vs. the commited file
