### ISSUE TITLE
is there any way to handle or ignore white space ?

### ISSUE THREAD

**Issue by ritwickdey** [fiduswriter/diffDOM#87]
I'm getting more `diff` object due to white space.

codesandbox: https://codesandbox.io/s/1oqk7qpw64

![image](https://user-images.githubusercontent.com/18099464/56637609-b08b9080-6689-11e9-83cc-cb33e4e0c259.png)

**Comment by Leland-Kwong** [comment]
One thing I did that seemed to help was trim the html.

**Comment by vielhuber** [comment]
What saved me is to call `Node.normalize()` before using diffDOM.
