### ISSUE TITLE
Problem with elements listeners after diff applied

### ISSUE THREAD

**Issue by ericferreira1992** [fiduswriter/diffDOM#94]
I using diffDOM passing nodes (Element) as parameters, like this:
`diff = dd.diff(oldTreeElement, newTreeElement);`
`dd.apply(oldTreeElement, diff);`

This is work, but when apply diff in `oldTreeElement` the eventListeners are lost. When in this example:

**oldTreeElement**
_outer html of element_:
`<ul>`
`   <li>Item 01</li>`
`   <li>Item 02</li>`
`</ul>`
____________________________________

**newTreeElement**
_outer html of element_:
`<ul>`
`   <li class="active">Item 01</li>`
`   <li>Item 02</li>`
`</ul>`

_Lister added in one children_:
`newTreeElement.children[0].addEventListener('click', (e) => {`
`    console.log('Teste');`
`});`
____________________________________
Thi way it change with success, but lost all eventListeners. What I think is it recreates the elements, and so the elements loses these events attached to them.

Do you can help me in this problem?

example sandbox: https://codesandbox.io/s/late-pond-4kyy4

**Comment by ericferreira1992** [comment]
Hello. I will close the thread because I managed to fix the problem in another way in my code.

**Comment by ericferreira1992** [comment]
I still have problems with the listeners added to the elements, I thought I could fix it, but the problem remains.

Below is a simple situation where the problem occurs. Initially **ul** has two **li** with a click listener on each of them. The button creates a new tree of elements identical to the current one, but does the _"Item 01"_ toggle (remove and put), always applying the listeners again. However, when the toggle is made to make "Item 01" appear again, his listener does not work.

https://codesandbox.io/s/late-pond-4kyy4

**Comment by jeremy21212121** [comment]
The code you linked to works for the first click. The second click there is a console error relating to an invalid attribute name "(aaa)" which is on line 39 of your code.

If you fix that invalid attribute name on line 39, your code works fine.

**Comment by ericferreira1992** [comment]
@jeremy21212121 
This problem not occours here, I'm opening the same link and works fine. Try open link again. Maybe it's some cache.

**Comment by Jeraldy** [comment]
@ericferreira1992 Did you managed to solve this... I'm facing the same issue here. After applying the diff all the listeners of the update nodes get lost. I have tried to go through the code and I realized that the dom elements are being re-created and the listeners get ignored.

**Comment by ericferreira1992** [comment]
@Jeraldy 
In my case, I was collecting all the listeners registered in the each elements (in an array) and removing them when diffDOM was run, then registering the listeners again. In the end, I had other problems and decided not to use the diffDOM library anymore and implementing my own.

**Comment by johanneswilm** [comment]
Hey,
in general diffDOM will only creates new elements and modify existing ones to the extend possibly. However, there are  exceptions to this rule, especially when the diffing occurs on a very complex set of nodes if diffDOM determines it's easier to recreate some nodes rather than moving them around.

If there is an addition that helps you with event listeners that you want to add, feel free to send in a patch.
