### ISSUE TITLE
redundant DOM changes

### ISSUE THREAD

**Issue by SqrTT** [fiduswriter/diffDOM#97]
diff makes many redundant changes: simple example to reproduce. 
https://jsfiddle.net/ajcqx21b/1/

for instance, in provided example, removes #shippingTypesShippingForm and then adds back

it starts behave correctly, once you remove space on line 19

**Comment by t3chguy** [comment]
Sounds like https://github.com/fiduswriter/diffDOM/issues/90

**Comment by johanneswilm** [comment]
This seems to have been fixed along with #90

**Comment by SqrTT** [comment]
thank you
